/**:
  ros__parameters:
    wheel_radius: 0.1375 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.090 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.545 # between front wheel center and rear wheel center
    wheel_tread: 0.550 # between left wheel center and right wheel center
    front_overhang: 0.1375 # between front wheel center and vehicle front
    rear_overhang: 0.1375 # between rear wheel center and vehicle rear
    left_overhang: 0.045 # between left wheel center and vehicle left
    right_overhang: 0.045 # between right wheel center and vehicle right
    vehicle_height: 0.310
    max_steer_angle: 0.3839724354 # [rad]
